package com.dcf.iqunxing.message2.entity;

import java.util.Date;

public class EmailMessageAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message_attachment.id
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message_attachment.email_message_id
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    private Long emailMessageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message_attachment.name
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message_attachment.path
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message_attachment.created_time
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_message_attachment.DataChange_LastTime
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    private Date datachangeLasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message_attachment.id
     *
     * @return the value of email_message_attachment.id
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message_attachment.id
     *
     * @param id the value for email_message_attachment.id
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message_attachment.email_message_id
     *
     * @return the value of email_message_attachment.email_message_id
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public Long getEmailMessageId() {
        return emailMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message_attachment.email_message_id
     *
     * @param emailMessageId the value for email_message_attachment.email_message_id
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public void setEmailMessageId(Long emailMessageId) {
        this.emailMessageId = emailMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message_attachment.name
     *
     * @return the value of email_message_attachment.name
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message_attachment.name
     *
     * @param name the value for email_message_attachment.name
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message_attachment.path
     *
     * @return the value of email_message_attachment.path
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message_attachment.path
     *
     * @param path the value for email_message_attachment.path
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message_attachment.created_time
     *
     * @return the value of email_message_attachment.created_time
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message_attachment.created_time
     *
     * @param createdTime the value for email_message_attachment.created_time
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_message_attachment.DataChange_LastTime
     *
     * @return the value of email_message_attachment.DataChange_LastTime
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_message_attachment.DataChange_LastTime
     *
     * @param datachangeLasttime the value for email_message_attachment.DataChange_LastTime
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}