package com.dcf.iqunxing.message2.entity;

import java.util.Date;

public class MessageJob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_job.id
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_job.last_schedule_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    private Date lastScheduleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_job.last_start_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    private Date lastStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_job.last_end_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    private Date lastEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_job.updated_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_job.created_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_job.DataChange_LastTime
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    private Date datachangeLasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_job.id
     *
     * @return the value of message_job.id
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_job.id
     *
     * @param id the value for message_job.id
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_job.last_schedule_time
     *
     * @return the value of message_job.last_schedule_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public Date getLastScheduleTime() {
        return lastScheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_job.last_schedule_time
     *
     * @param lastScheduleTime the value for message_job.last_schedule_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public void setLastScheduleTime(Date lastScheduleTime) {
        this.lastScheduleTime = lastScheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_job.last_start_time
     *
     * @return the value of message_job.last_start_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public Date getLastStartTime() {
        return lastStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_job.last_start_time
     *
     * @param lastStartTime the value for message_job.last_start_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public void setLastStartTime(Date lastStartTime) {
        this.lastStartTime = lastStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_job.last_end_time
     *
     * @return the value of message_job.last_end_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public Date getLastEndTime() {
        return lastEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_job.last_end_time
     *
     * @param lastEndTime the value for message_job.last_end_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public void setLastEndTime(Date lastEndTime) {
        this.lastEndTime = lastEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_job.updated_time
     *
     * @return the value of message_job.updated_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_job.updated_time
     *
     * @param updatedTime the value for message_job.updated_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_job.created_time
     *
     * @return the value of message_job.created_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_job.created_time
     *
     * @param createdTime the value for message_job.created_time
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_job.DataChange_LastTime
     *
     * @return the value of message_job.DataChange_LastTime
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_job.DataChange_LastTime
     *
     * @param datachangeLasttime the value for message_job.DataChange_LastTime
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}