package com.dcf.iqunxing.message2.entity;

import java.util.Date;

public class PushMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.push_message_template_id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private Long pushMessageTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.receiver_id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private String receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.device_id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.device_type
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private Byte deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.priority
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private Byte priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.state
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.immediate
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private Byte immediate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.schedule_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private Date scheduleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.expire_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.sent_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private Date sentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.sent_result
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private String sentResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.created_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.created_by
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.DataChange_LastTime
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    private Date datachangeLasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.id
     *
     * @return the value of push_message.id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.id
     *
     * @param id the value for push_message.id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.push_message_template_id
     *
     * @return the value of push_message.push_message_template_id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public Long getPushMessageTemplateId() {
        return pushMessageTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.push_message_template_id
     *
     * @param pushMessageTemplateId the value for push_message.push_message_template_id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setPushMessageTemplateId(Long pushMessageTemplateId) {
        this.pushMessageTemplateId = pushMessageTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.receiver_id
     *
     * @return the value of push_message.receiver_id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.receiver_id
     *
     * @param receiverId the value for push_message.receiver_id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId == null ? null : receiverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.device_id
     *
     * @return the value of push_message.device_id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.device_id
     *
     * @param deviceId the value for push_message.device_id
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.device_type
     *
     * @return the value of push_message.device_type
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public Byte getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.device_type
     *
     * @param deviceType the value for push_message.device_type
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setDeviceType(Byte deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.priority
     *
     * @return the value of push_message.priority
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public Byte getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.priority
     *
     * @param priority the value for push_message.priority
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setPriority(Byte priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.state
     *
     * @return the value of push_message.state
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.state
     *
     * @param state the value for push_message.state
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.immediate
     *
     * @return the value of push_message.immediate
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public Byte getImmediate() {
        return immediate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.immediate
     *
     * @param immediate the value for push_message.immediate
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setImmediate(Byte immediate) {
        this.immediate = immediate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.schedule_time
     *
     * @return the value of push_message.schedule_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public Date getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.schedule_time
     *
     * @param scheduleTime the value for push_message.schedule_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setScheduleTime(Date scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.expire_time
     *
     * @return the value of push_message.expire_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.expire_time
     *
     * @param expireTime the value for push_message.expire_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.sent_time
     *
     * @return the value of push_message.sent_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public Date getSentTime() {
        return sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.sent_time
     *
     * @param sentTime the value for push_message.sent_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setSentTime(Date sentTime) {
        this.sentTime = sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.sent_result
     *
     * @return the value of push_message.sent_result
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public String getSentResult() {
        return sentResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.sent_result
     *
     * @param sentResult the value for push_message.sent_result
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setSentResult(String sentResult) {
        this.sentResult = sentResult == null ? null : sentResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.created_time
     *
     * @return the value of push_message.created_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.created_time
     *
     * @param createdTime the value for push_message.created_time
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.created_by
     *
     * @return the value of push_message.created_by
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.created_by
     *
     * @param createdBy the value for push_message.created_by
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.DataChange_LastTime
     *
     * @return the value of push_message.DataChange_LastTime
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.DataChange_LastTime
     *
     * @param datachangeLasttime the value for push_message.DataChange_LastTime
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}