package com.dcf.iqunxing.message2.entity;

import java.util.Date;

public class SiteMessageProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_property.id
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_property.site_message_id
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    private Long siteMessageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_property.prop_key
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    private String propKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_property.prop_value
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    private String propValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_property.created_time
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_property.DataChange_LastTime
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    private Date datachangeLasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_property.id
     *
     * @return the value of site_message_property.id
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_property.id
     *
     * @param id the value for site_message_property.id
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_property.site_message_id
     *
     * @return the value of site_message_property.site_message_id
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public Long getSiteMessageId() {
        return siteMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_property.site_message_id
     *
     * @param siteMessageId the value for site_message_property.site_message_id
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public void setSiteMessageId(Long siteMessageId) {
        this.siteMessageId = siteMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_property.prop_key
     *
     * @return the value of site_message_property.prop_key
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public String getPropKey() {
        return propKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_property.prop_key
     *
     * @param propKey the value for site_message_property.prop_key
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public void setPropKey(String propKey) {
        this.propKey = propKey == null ? null : propKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_property.prop_value
     *
     * @return the value of site_message_property.prop_value
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public String getPropValue() {
        return propValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_property.prop_value
     *
     * @param propValue the value for site_message_property.prop_value
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public void setPropValue(String propValue) {
        this.propValue = propValue == null ? null : propValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_property.created_time
     *
     * @return the value of site_message_property.created_time
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_property.created_time
     *
     * @param createdTime the value for site_message_property.created_time
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_property.DataChange_LastTime
     *
     * @return the value of site_message_property.DataChange_LastTime
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_property.DataChange_LastTime
     *
     * @param datachangeLasttime the value for site_message_property.DataChange_LastTime
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}