package com.dcf.iqunxing.message2.entity;

import java.util.Date;

public class SiteMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.id
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.site_message_content_id
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Long siteMessageContentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.receiver_id
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private String receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.sender
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.type
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.priority
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Byte priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.state
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.immediate
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Byte immediate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.schedule_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Date scheduleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.expired_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Date expiredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.sent_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Date sentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.read_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Date readTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.processed_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Date processedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.deleted_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Date deletedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.deleted
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.created_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message.datachange_lasttime
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    private Date datachangeLasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.id
     *
     * @return the value of site_message.id
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.id
     *
     * @param id the value for site_message.id
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.site_message_content_id
     *
     * @return the value of site_message.site_message_content_id
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Long getSiteMessageContentId() {
        return siteMessageContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.site_message_content_id
     *
     * @param siteMessageContentId the value for site_message.site_message_content_id
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setSiteMessageContentId(Long siteMessageContentId) {
        this.siteMessageContentId = siteMessageContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.receiver_id
     *
     * @return the value of site_message.receiver_id
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.receiver_id
     *
     * @param receiverId the value for site_message.receiver_id
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId == null ? null : receiverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.sender
     *
     * @return the value of site_message.sender
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.sender
     *
     * @param sender the value for site_message.sender
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.type
     *
     * @return the value of site_message.type
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.type
     *
     * @param type the value for site_message.type
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.priority
     *
     * @return the value of site_message.priority
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Byte getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.priority
     *
     * @param priority the value for site_message.priority
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setPriority(Byte priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.state
     *
     * @return the value of site_message.state
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.state
     *
     * @param state the value for site_message.state
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.immediate
     *
     * @return the value of site_message.immediate
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Byte getImmediate() {
        return immediate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.immediate
     *
     * @param immediate the value for site_message.immediate
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setImmediate(Byte immediate) {
        this.immediate = immediate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.schedule_time
     *
     * @return the value of site_message.schedule_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Date getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.schedule_time
     *
     * @param scheduleTime the value for site_message.schedule_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setScheduleTime(Date scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.expired_time
     *
     * @return the value of site_message.expired_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.expired_time
     *
     * @param expiredTime the value for site_message.expired_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.sent_time
     *
     * @return the value of site_message.sent_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Date getSentTime() {
        return sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.sent_time
     *
     * @param sentTime the value for site_message.sent_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setSentTime(Date sentTime) {
        this.sentTime = sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.read_time
     *
     * @return the value of site_message.read_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.read_time
     *
     * @param readTime the value for site_message.read_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.processed_time
     *
     * @return the value of site_message.processed_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Date getProcessedTime() {
        return processedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.processed_time
     *
     * @param processedTime the value for site_message.processed_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setProcessedTime(Date processedTime) {
        this.processedTime = processedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.deleted_time
     *
     * @return the value of site_message.deleted_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Date getDeletedTime() {
        return deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.deleted_time
     *
     * @param deletedTime the value for site_message.deleted_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setDeletedTime(Date deletedTime) {
        this.deletedTime = deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.deleted
     *
     * @return the value of site_message.deleted
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.deleted
     *
     * @param deleted the value for site_message.deleted
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.created_time
     *
     * @return the value of site_message.created_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.created_time
     *
     * @param createdTime the value for site_message.created_time
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message.datachange_lasttime
     *
     * @return the value of site_message.datachange_lasttime
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message.datachange_lasttime
     *
     * @param datachangeLasttime the value for site_message.datachange_lasttime
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}