package com.dcf.iqunxing.message2.entity;

import java.util.Date;

public class SiteMessageContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_content.id
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_content.site_message_template_id
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    private Long siteMessageTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_content.title
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_content.content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_content.addition
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    private String addition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_content.type
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_content.created_time
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_content.created_by
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_content.updated_time
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_content.updated_by
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_message_content.DataChange_LastTime
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    private Date datachangeLasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_content.id
     *
     * @return the value of site_message_content.id
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_content.id
     *
     * @param id the value for site_message_content.id
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_content.site_message_template_id
     *
     * @return the value of site_message_content.site_message_template_id
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public Long getSiteMessageTemplateId() {
        return siteMessageTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_content.site_message_template_id
     *
     * @param siteMessageTemplateId the value for site_message_content.site_message_template_id
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public void setSiteMessageTemplateId(Long siteMessageTemplateId) {
        this.siteMessageTemplateId = siteMessageTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_content.title
     *
     * @return the value of site_message_content.title
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_content.title
     *
     * @param title the value for site_message_content.title
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_content.content
     *
     * @return the value of site_message_content.content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_content.content
     *
     * @param content the value for site_message_content.content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_content.addition
     *
     * @return the value of site_message_content.addition
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public String getAddition() {
        return addition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_content.addition
     *
     * @param addition the value for site_message_content.addition
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public void setAddition(String addition) {
        this.addition = addition == null ? null : addition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_content.type
     *
     * @return the value of site_message_content.type
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_content.type
     *
     * @param type the value for site_message_content.type
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_content.created_time
     *
     * @return the value of site_message_content.created_time
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_content.created_time
     *
     * @param createdTime the value for site_message_content.created_time
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_content.created_by
     *
     * @return the value of site_message_content.created_by
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_content.created_by
     *
     * @param createdBy the value for site_message_content.created_by
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_content.updated_time
     *
     * @return the value of site_message_content.updated_time
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_content.updated_time
     *
     * @param updatedTime the value for site_message_content.updated_time
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_content.updated_by
     *
     * @return the value of site_message_content.updated_by
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_content.updated_by
     *
     * @param updatedBy the value for site_message_content.updated_by
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_message_content.DataChange_LastTime
     *
     * @return the value of site_message_content.DataChange_LastTime
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_message_content.DataChange_LastTime
     *
     * @param datachangeLasttime the value for site_message_content.DataChange_LastTime
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}