package com.dcf.iqunxing.message2.entity;

import java.util.Date;

public class SmsMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.id
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.sms_message_template_id
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private Long smsMessageTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.mobiles
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private String mobiles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.priority
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private Byte priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.state
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.immediate
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private Byte immediate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.schedule_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private Date scheduleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.expired_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private Date expiredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.sent_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private Date sentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.sent_result
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private String sentResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.created_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.created_by
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message.DataChange_LastTime
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    private Date datachangeLasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.id
     *
     * @return the value of sms_message.id
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.id
     *
     * @param id the value for sms_message.id
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.sms_message_template_id
     *
     * @return the value of sms_message.sms_message_template_id
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public Long getSmsMessageTemplateId() {
        return smsMessageTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.sms_message_template_id
     *
     * @param smsMessageTemplateId the value for sms_message.sms_message_template_id
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setSmsMessageTemplateId(Long smsMessageTemplateId) {
        this.smsMessageTemplateId = smsMessageTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.mobiles
     *
     * @return the value of sms_message.mobiles
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public String getMobiles() {
        return mobiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.mobiles
     *
     * @param mobiles the value for sms_message.mobiles
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setMobiles(String mobiles) {
        this.mobiles = mobiles == null ? null : mobiles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.priority
     *
     * @return the value of sms_message.priority
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public Byte getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.priority
     *
     * @param priority the value for sms_message.priority
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setPriority(Byte priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.state
     *
     * @return the value of sms_message.state
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.state
     *
     * @param state the value for sms_message.state
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.immediate
     *
     * @return the value of sms_message.immediate
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public Byte getImmediate() {
        return immediate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.immediate
     *
     * @param immediate the value for sms_message.immediate
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setImmediate(Byte immediate) {
        this.immediate = immediate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.schedule_time
     *
     * @return the value of sms_message.schedule_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public Date getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.schedule_time
     *
     * @param scheduleTime the value for sms_message.schedule_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setScheduleTime(Date scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.expired_time
     *
     * @return the value of sms_message.expired_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.expired_time
     *
     * @param expiredTime the value for sms_message.expired_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.sent_time
     *
     * @return the value of sms_message.sent_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public Date getSentTime() {
        return sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.sent_time
     *
     * @param sentTime the value for sms_message.sent_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setSentTime(Date sentTime) {
        this.sentTime = sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.sent_result
     *
     * @return the value of sms_message.sent_result
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public String getSentResult() {
        return sentResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.sent_result
     *
     * @param sentResult the value for sms_message.sent_result
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setSentResult(String sentResult) {
        this.sentResult = sentResult == null ? null : sentResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.created_time
     *
     * @return the value of sms_message.created_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.created_time
     *
     * @param createdTime the value for sms_message.created_time
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.created_by
     *
     * @return the value of sms_message.created_by
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.created_by
     *
     * @param createdBy the value for sms_message.created_by
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message.DataChange_LastTime
     *
     * @return the value of sms_message.DataChange_LastTime
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message.DataChange_LastTime
     *
     * @param datachangeLasttime the value for sms_message.DataChange_LastTime
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}