package com.dcf.iqunxing.message2.entity;

import java.util.Date;

public class SmsMessageProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message_property.id
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message_property.sms_message_id
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    private Long smsMessageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message_property.prop_key
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    private String propKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message_property.prop_value
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    private String propValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message_property.created_time
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_message_property.DataChange_LastTime
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    private Date datachangeLasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message_property.id
     *
     * @return the value of sms_message_property.id
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message_property.id
     *
     * @param id the value for sms_message_property.id
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message_property.sms_message_id
     *
     * @return the value of sms_message_property.sms_message_id
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public Long getSmsMessageId() {
        return smsMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message_property.sms_message_id
     *
     * @param smsMessageId the value for sms_message_property.sms_message_id
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public void setSmsMessageId(Long smsMessageId) {
        this.smsMessageId = smsMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message_property.prop_key
     *
     * @return the value of sms_message_property.prop_key
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public String getPropKey() {
        return propKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message_property.prop_key
     *
     * @param propKey the value for sms_message_property.prop_key
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public void setPropKey(String propKey) {
        this.propKey = propKey == null ? null : propKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message_property.prop_value
     *
     * @return the value of sms_message_property.prop_value
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public String getPropValue() {
        return propValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message_property.prop_value
     *
     * @param propValue the value for sms_message_property.prop_value
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public void setPropValue(String propValue) {
        this.propValue = propValue == null ? null : propValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message_property.created_time
     *
     * @return the value of sms_message_property.created_time
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message_property.created_time
     *
     * @param createdTime the value for sms_message_property.created_time
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_message_property.DataChange_LastTime
     *
     * @return the value of sms_message_property.DataChange_LastTime
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_message_property.DataChange_LastTime
     *
     * @param datachangeLasttime the value for sms_message_property.DataChange_LastTime
     *
     * @mbggenerated Fri Aug 14 19:21:34 CST 2015
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}