package com.dcf.iqunxing.message2.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dcf.iqunxing.message2.entity.EmailMessageTemplate;
import com.dcf.iqunxing.message2.entity.EmailMessageTemplateExample;

public interface EmailMessageTemplateMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_template
     *
     * @mbggenerated Mon Feb 22 15:00:46 CST 2016
     */
    int countByExample(EmailMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_template
     *
     * @mbggenerated Mon Feb 22 15:00:46 CST 2016
     */
    int deleteByExample(EmailMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_template
     *
     * @mbggenerated Mon Feb 22 15:00:46 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_template
     *
     * @mbggenerated Mon Feb 22 15:00:46 CST 2016
     */
    int insert(EmailMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_template
     *
     * @mbggenerated Mon Feb 22 15:00:46 CST 2016
     */
    int insertSelective(EmailMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_template
     *
     * @mbggenerated Mon Feb 22 15:00:46 CST 2016
     */
    List<EmailMessageTemplate> selectByExample(EmailMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_template
     *
     * @mbggenerated Mon Feb 22 15:00:46 CST 2016
     */
    EmailMessageTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_template
     *
     * @mbggenerated Mon Feb 22 15:00:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") EmailMessageTemplate record, @Param("example") EmailMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_template
     *
     * @mbggenerated Mon Feb 22 15:00:46 CST 2016
     */
    int updateByExample(@Param("record") EmailMessageTemplate record, @Param("example") EmailMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_template
     *
     * @mbggenerated Mon Feb 22 15:00:46 CST 2016
     */
    int updateByPrimaryKeySelective(EmailMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_template
     *
     * @mbggenerated Mon Feb 22 15:00:46 CST 2016
     */
    int updateByPrimaryKey(EmailMessageTemplate record);
}
