package com.dcf.iqunxing.message2.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dcf.iqunxing.message2.entity.EmailMessageAttachment;
import com.dcf.iqunxing.message2.entity.EmailMessageAttachmentExample;

public interface EmailMessageAttachmentMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_attachment
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    int countByExample(EmailMessageAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_attachment
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    int deleteByExample(EmailMessageAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_attachment
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_attachment
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    int insert(EmailMessageAttachment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_attachment
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    int insertSelective(EmailMessageAttachment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_attachment
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    List<EmailMessageAttachment> selectByExample(EmailMessageAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_attachment
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    EmailMessageAttachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_attachment
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    int updateByExampleSelective(@Param("record") EmailMessageAttachment record,
            @Param("example") EmailMessageAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_attachment
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    int updateByExample(@Param("record") EmailMessageAttachment record, @Param("example") EmailMessageAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_attachment
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    int updateByPrimaryKeySelective(EmailMessageAttachment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table email_message_attachment
     *
     * @mbggenerated Mon Aug 10 15:05:04 CST 2015
     */
    int updateByPrimaryKey(EmailMessageAttachment record);
}
