package com.dcf.iqunxing.message2.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dcf.iqunxing.message2.entity.MessageJob;
import com.dcf.iqunxing.message2.entity.MessageJobExample;

public interface MessageJobMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message_job
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    int countByExample(MessageJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message_job
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    int deleteByExample(MessageJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message_job
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message_job
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    int insert(MessageJob record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message_job
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    int insertSelective(MessageJob record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message_job
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    List<MessageJob> selectByExample(MessageJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message_job
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    MessageJob selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message_job
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    int updateByExampleSelective(@Param("record") MessageJob record, @Param("example") MessageJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message_job
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    int updateByExample(@Param("record") MessageJob record, @Param("example") MessageJobExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message_job
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    int updateByPrimaryKeySelective(MessageJob record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message_job
     *
     * @mbggenerated Wed Aug 05 18:13:59 CST 2015
     */
    int updateByPrimaryKey(MessageJob record);
  
    /**
     * 获取全部
     * @return
     */
	List<MessageJob> selectAll();
}
