package com.dcf.iqunxing.message2.dao;

import com.dcf.iqunxing.message2.entity.PushMessageProperty;
import com.dcf.iqunxing.message2.entity.PushMessagePropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PushMessagePropertyMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table push_message_property
     * @mbggenerated  Fri Aug 21 18:38:59 CST 2015
     */
    int countByExample(PushMessagePropertyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table push_message_property
     * @mbggenerated  Fri Aug 21 18:38:59 CST 2015
     */
    int deleteByExample(PushMessagePropertyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table push_message_property
     * @mbggenerated  Fri Aug 21 18:38:59 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table push_message_property
     * @mbggenerated  Fri Aug 21 18:38:59 CST 2015
     */
    int insert(PushMessageProperty record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table push_message_property
     * @mbggenerated  Fri Aug 21 18:38:59 CST 2015
     */
    int insertSelective(PushMessageProperty record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table push_message_property
     * @mbggenerated  Fri Aug 21 18:38:59 CST 2015
     */
    List<PushMessageProperty> selectByExample(PushMessagePropertyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table push_message_property
     * @mbggenerated  Fri Aug 21 18:38:59 CST 2015
     */
    PushMessageProperty selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table push_message_property
     * @mbggenerated  Fri Aug 21 18:38:59 CST 2015
     */
    int updateByExampleSelective(@Param("record") PushMessageProperty record, @Param("example") PushMessagePropertyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table push_message_property
     * @mbggenerated  Fri Aug 21 18:38:59 CST 2015
     */
    int updateByExample(@Param("record") PushMessageProperty record, @Param("example") PushMessagePropertyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table push_message_property
     * @mbggenerated  Fri Aug 21 18:38:59 CST 2015
     */
    int updateByPrimaryKeySelective(PushMessageProperty record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table push_message_property
     * @mbggenerated  Fri Aug 21 18:38:59 CST 2015
     */
    int updateByPrimaryKey(PushMessageProperty record);
}