package com.dcf.iqunxing.message2.dao;

import com.dcf.iqunxing.message2.entity.PushMessage;
import com.dcf.iqunxing.message2.entity.PushMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PushMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    int countByExample(PushMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    int deleteByExample(PushMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    int insert(PushMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    int insertSelective(PushMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    List<PushMessage> selectByExample(PushMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    PushMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") PushMessage record, @Param("example") PushMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    int updateByExample(@Param("record") PushMessage record, @Param("example") PushMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    int updateByPrimaryKeySelective(PushMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push_message
     *
     * @mbggenerated Fri Aug 21 18:25:24 CST 2015
     */
    int updateByPrimaryKey(PushMessage record);
}