package com.dcf.iqunxing.message2.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dcf.iqunxing.message2.entity.SiteMessage;
import com.dcf.iqunxing.message2.entity.SiteMessageExample;

public interface SiteMessageMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    int countByExample(SiteMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    int deleteByExample(SiteMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    int insert(SiteMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    int insertSelective(SiteMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    List<SiteMessage> selectByExample(SiteMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    SiteMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") SiteMessage record, @Param("example") SiteMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    int updateByExample(@Param("record") SiteMessage record, @Param("example") SiteMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    int updateByPrimaryKeySelective(SiteMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message
     *
     * @mbggenerated Thu Jan 14 17:09:13 CST 2016
     */
    int updateByPrimaryKey(SiteMessage record);
}
