package com.dcf.iqunxing.message2.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dcf.iqunxing.message2.entity.SiteMessageContent;
import com.dcf.iqunxing.message2.entity.SiteMessageContentExample;

public interface SiteMessageContentMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    int countByExample(SiteMessageContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    int deleteByExample(SiteMessageContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    int insert(SiteMessageContent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    int insertSelective(SiteMessageContent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    List<SiteMessageContent> selectByExample(SiteMessageContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    SiteMessageContent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") SiteMessageContent record, @Param("example") SiteMessageContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    int updateByExample(@Param("record") SiteMessageContent record, @Param("example") SiteMessageContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    int updateByPrimaryKeySelective(SiteMessageContent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_content
     *
     * @mbggenerated Mon Aug 24 10:35:39 CST 2015
     */
    int updateByPrimaryKey(SiteMessageContent record);
}
