package com.dcf.iqunxing.message2.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dcf.iqunxing.message2.entity.SiteMessageProperty;
import com.dcf.iqunxing.message2.entity.SiteMessagePropertyExample;

public interface SiteMessagePropertyMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_property
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    int countByExample(SiteMessagePropertyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_property
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    int deleteByExample(SiteMessagePropertyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_property
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_property
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    int insert(SiteMessageProperty record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_property
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    int insertSelective(SiteMessageProperty record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_property
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    List<SiteMessageProperty> selectByExample(SiteMessagePropertyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_property
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    SiteMessageProperty selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_property
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") SiteMessageProperty record, @Param("example") SiteMessagePropertyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_property
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    int updateByExample(@Param("record") SiteMessageProperty record, @Param("example") SiteMessagePropertyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_property
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    int updateByPrimaryKeySelective(SiteMessageProperty record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_property
     *
     * @mbggenerated Tue Aug 25 10:28:43 CST 2015
     */
    int updateByPrimaryKey(SiteMessageProperty record);
}
