package com.dcf.iqunxing.message2.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dcf.iqunxing.message2.entity.SiteMessageTemplate;
import com.dcf.iqunxing.message2.entity.SiteMessageTemplateExample;

public interface SiteMessageTemplateMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_template
     *
     * @mbggenerated Mon Feb 22 15:03:34 CST 2016
     */
    int countByExample(SiteMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_template
     *
     * @mbggenerated Mon Feb 22 15:03:34 CST 2016
     */
    int deleteByExample(SiteMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_template
     *
     * @mbggenerated Mon Feb 22 15:03:34 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_template
     *
     * @mbggenerated Mon Feb 22 15:03:34 CST 2016
     */
    int insert(SiteMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_template
     *
     * @mbggenerated Mon Feb 22 15:03:34 CST 2016
     */
    int insertSelective(SiteMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_template
     *
     * @mbggenerated Mon Feb 22 15:03:34 CST 2016
     */
    List<SiteMessageTemplate> selectByExample(SiteMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_template
     *
     * @mbggenerated Mon Feb 22 15:03:34 CST 2016
     */
    SiteMessageTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_template
     *
     * @mbggenerated Mon Feb 22 15:03:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") SiteMessageTemplate record, @Param("example") SiteMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_template
     *
     * @mbggenerated Mon Feb 22 15:03:34 CST 2016
     */
    int updateByExample(@Param("record") SiteMessageTemplate record, @Param("example") SiteMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_template
     *
     * @mbggenerated Mon Feb 22 15:03:34 CST 2016
     */
    int updateByPrimaryKeySelective(SiteMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table site_message_template
     *
     * @mbggenerated Mon Feb 22 15:03:34 CST 2016
     */
    int updateByPrimaryKey(SiteMessageTemplate record);
}
