package com.dcf.iqunxing.message2.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dcf.iqunxing.message2.entity.SmsMessage;
import com.dcf.iqunxing.message2.entity.SmsMessageExample;

public interface SmsMessageMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    int countByExample(SmsMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    int deleteByExample(SmsMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    int insert(SmsMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    int insertSelective(SmsMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    List<SmsMessage> selectByExample(SmsMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    SmsMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    int updateByExampleSelective(@Param("record") SmsMessage record, @Param("example") SmsMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    int updateByExample(@Param("record") SmsMessage record, @Param("example") SmsMessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    int updateByPrimaryKeySelective(SmsMessage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message
     *
     * @mbggenerated Mon Aug 10 15:03:32 CST 2015
     */
    int updateByPrimaryKey(SmsMessage record);
}
