package com.dcf.iqunxing.message2.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dcf.iqunxing.message2.entity.SmsMessageTemplate;
import com.dcf.iqunxing.message2.entity.SmsMessageTemplateExample;

public interface SmsMessageTemplateMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Feb 22 15:04:21 CST 2016
     */
    int countByExample(SmsMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Feb 22 15:04:21 CST 2016
     */
    int deleteByExample(SmsMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Feb 22 15:04:21 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Feb 22 15:04:21 CST 2016
     */
    int insert(SmsMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Feb 22 15:04:21 CST 2016
     */
    int insertSelective(SmsMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Feb 22 15:04:21 CST 2016
     */
    List<SmsMessageTemplate> selectByExample(SmsMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Feb 22 15:04:21 CST 2016
     */
    SmsMessageTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Feb 22 15:04:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") SmsMessageTemplate record, @Param("example") SmsMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Feb 22 15:04:21 CST 2016
     */
    int updateByExample(@Param("record") SmsMessageTemplate record, @Param("example") SmsMessageTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Feb 22 15:04:21 CST 2016
     */
    int updateByPrimaryKeySelective(SmsMessageTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Feb 22 15:04:21 CST 2016
     */
    int updateByPrimaryKey(SmsMessageTemplate record);
}
