package com.dcf.iqunxing.message2.dao;

import java.util.List;

import com.dcf.iqunxing.message2.entity.TemplateUnion;
import com.dcf.iqunxing.message2.entity.TemplateUnionExample;

public interface TemplateUnionMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Dec 21 11:05:27 CST 2015
     */
    int countByExample(TemplateUnionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sms_message_template
     *
     * @mbggenerated Mon Dec 21 11:05:27 CST 2015
     */
    List<TemplateUnion> selectByExample(TemplateUnionExample example);

}
